snmpd: always exit after displaying usage
net-snmp/net-snmp pull request #337
Opened 2021-08-27 11:45 UTC by kunkku

Currently, viewing the help text with `-h` results in `snmpd` being started in the background, whereas this does not happen with `--help`. Similarly, when an error is detected in command line syntax, the help text is displayed but sometimes `snmpd` gets started anyway, depending on the execution path.

This patch makes `snmpd` consistently terminate whenever the `usage` function gets called. It also removes the `break` and `goto` statements no longer needed.

2021-08-28 02:16 UTC, bvanassche requested changes

2021-08-28 02:16 UTC, bvanassche commented on agent/snmpd.c
> -            break;
So there are more `usage()` calls than I had realized. How about keeping the `exit()` call in the `usage()` function and making sure that no new compiler warnings are triggered?

2021-09-02 16:25 UTC, kunkku commented on agent/snmpd.c
> -            break;
Patch updated to keep the `break` statements intact.

2021-09-03 04:52 UTC, bvanassche commented
This patch has been applied on the v5.9 and master branches. Thanks for the patch!

2021-09-03 04:52 UTC, closed without merging