Free new type variable. May cause memory leaks.
net-snmp/net-snmp pull request #440
Opened 2022-07-26 09:00 UTC by zxlin96

2022-07-26 23:22 UTC, bvanassche commented
The patch description is confusing to me. Does the description mean that this patch may introduce a memory leak? If not, please rephrase the patch description.

2022-07-27 15:56 UTC, fenner requested changes

2022-07-27 15:56 UTC, fenner commented on snmplib/snmp_api.c
> +            return i;    /* '�' is the first differing subidentifier
What is the goal of this change?  What is the new character inside the quotes?  Github can't render it.

2022-07-27 15:56 UTC, fenner commented on snmplib/snmp_api.c
> +        SNMP_FREE(var->val.objid);
Given that string, bitstring and objid are all pointers inside the same union, can you please explain how these are different than operating on `string`?

```C
typedef union {
   long           *integer;
   u_char         *string;
   oid            *objid;
   u_char         *bitstring;
   struct counter64 *counter64;
#ifdef NETSNMP_WITH_OPAQUE_SPECIAL_TYPES
   float          *floatVal;
   double         *doubleVal;
   /*
    * t_union *unionVal; 
    */
#endif                          /* NETSNMP_WITH_OPAQUE_SPECIAL_TYPES */
} netsnmp_vardata;
```

2022-08-19 19:37 UTC, fenner commented
Closing due to no response.  (Note that the regular tests show that nearly every test fails with this change.)

2022-08-19 19:37 UTC, closed without merging