Disallow SET requests with NULL varbind
net-snmp/net-snmp pull request #490
Opened 2022-11-27 18:41 UTC by fenner

I'm creating a pull request here just to solicit reviews - I can obviously commit myself if we decide this is right.

This is my reaction to #474 and #475 - both of these are because the SET code doesn't check the incoming type at all, and assume that the integer member of the union is set.  But for a NULL type, the pointer is NULL.

There are still problems with MIB module implementations that do not check the varbind type - what does it mean to set the ipDefaultTTL to an OBJECT-IDENTIFIER?  So there are still opportunities for cleanup; every SET_RESERVE1 should call `netsnmp_check_vb_type()` - but NULL is the only case where the pointer will be invalid, so this patch eliminates the possibility that a module implementation will naively dereference a NULL pointer.

2022-11-28 16:22 UTC, bvanassche requested changes

2022-11-30 17:30 UTC, hardaker commented on agent/snmp_agent.c
> +    case SNMP_MSG_SET:
I agree ideally it should be in a helper function so that some weird mib implementation that wants to accept NULLs can remove it.

2022-12-09 18:38 UTC, bvanassche commented
The new version looks good to me.

2022-12-28 08:49 UTC, XWwalker commented
This looks good, when will this PR fix be approved?

2022-12-29 13:56 UTC, bvanassche commented
@fenner , do you plan to merge this pull request yourself?

2022-12-29 15:08 UTC, fenner commented
@bvanassche yes, is it ok to merge to the 5.9.3 branch?

2022-12-29 15:11 UTC, bvanassche commented
> @bvanassche yes, is it ok to merge to the 5.9.3 branch?

Are there plans for a release with version number 5.9.3.1? If not, I think these patches should either be merged into the 5.9 branch or into the master branch.

2022-12-29 15:19 UTC, fenner commented
> > @bvanassche yes, is it ok to merge to the 5.9.3 branch?
> 
> Are there plans for a release with version number 5.9.3.1? If not, I think these patches should either be merged into the 5.9 branch or into the master branch.

I was confused by recent commits on the 5.9.3 branch.  I will merge into 5.9.

2022-12-29 15:20 UTC, merged

2022-12-29 15:32 UTC, bvanassche commented
> I was confused by recent commits on the 5.9.3 branch. I will merge into 5.9.

The recent changes I made on the 5.9.3 branch fix issues that I encountered while generating Windows binaries for version v5.9.3.